### ISSUE TITLE
Code not available?

### ISSUE THREAD

**Issue by Chris2011** [khalidt/NetBeans-Plugin#1]
I forked your repo but there is no code, only the nbm file and screenshots, please provide the code, I want to make pull requests.

Regards

Chris

**Comment by khalidt** [comment]
Sorry for that, because i lost the source code i didn't provide it. Now its ready I rewrite it again

Regards

**Comment by Chris2011** [comment]
Great, thx :)

**Comment by khalidt** [comment]
your welcome
